### ISSUE TITLE
Enhancement: Run tests when file is changed or saved --watch

### ISSUE THREAD

**Issue by kgividen** [JetBrains/mocha-intellij#1]
I don't see a way to do a --watch so it will automatically run tests when the files are saved.  Is this currently possible?

**Comment by segrey** [comment]
Option `--watch` isn't supported
You can toggle automatic rerun of tests on code changes - see a button on the toolbar.

**Comment by kgividen** [comment]
Ah I see the button now.  I was running them as debug before so I missed it.  Thanks!
