### ISSUE TITLE
Theoretical bug in "before all" hook detection 

### ISSUE THREAD

**Issue by boneskull** [JetBrains/mocha-intellij#4]
Hooks can have a user-defined `title` which is always appended to the default. In the case of  "before all" hooks, the default is `'"before all" hook`.  Given the reporter's logic, it may fail to recognize a "before all" hook with a custom title. 

"Before each" hooks do not seem to have this problem, and are determined differently. Haven't looked at the "after" hooks implementation.

**Comment by segrey** [comment]
Thanks, reproduced with

``` javascript
describe('hooks', function() {

  before(function custom() {
    // runs before all tests in this block
    require('assert').fail();
  });

  it('my test', function () {
  });
});
```
