### ISSUE TITLE
Plugin does not correctly show describe statement for skipped dynamically generated tests

### ISSUE THREAD

**Issue by NazarioJL** [JetBrains/mocha-intellij#5]
The mocha intellij plugin will not correctly show describe statements for skipped tests. 

For example:

```
const assert = require('assert');

describe.only('Mocha issues with skipped tests', function() {
  describe('Skip one, not the other', function() {
    it.skip('Skip', function() {
      //this.skip();
    });

    it('Do not skip', function() {
      assert.equal(true, true);
    });
  })
});
```

Generates the following output in mocha:

```
> mocha



  Mocha issues with skipped tests
    Skip one, not the other
      - Skip
      ✓ Do not skip


  1 passing (6ms)
  1 pending
```

However the UI does not show the *Skip* test. 

See the following image:

![screenshot from 2016-11-21 16-10-13](https://cloud.githubusercontent.com/assets/3681596/20505901/019a6624-b005-11e6-88bc-30baedf70008.png)

I would expect to see the skipped tests as well. This can be problematic when tests are dynamically generated. For example:

```

const assert = require('assert');

describe('Mocha issues with generated tests', function () {

    let tests = ['one', 'two'];

    // generate tests
    tests.forEach(function (test) {
        describe(`Test for -> ${test}`, function () {

            it(`it() statement on ${test}`, function () {
                if (test === 'two') {
                    this.skip();
                }
                assert.equal(true, true);
            });
        });
    });
});
```

The seconds describe (Test for -> two) will not even show as a node.

**Comment by segrey** [comment]
To show the **Skip** test, toggle on "Show Ignored" button:
![show-ignored](https://cloud.githubusercontent.com/assets/607109/20519535/579d17c4-b0b4-11e6-9be0-cd97b6393258.png)

**Comment by NazarioJL** [comment]
Missed that button! Thanks!
