### ISSUE TITLE
live templates for Mocha

### ISSUE THREAD

**Issue by boneskull** [JetBrains/mocha-intellij#7]
Not sure where [these](https://gist.github.com/boneskull/1b9a02cee22aac53dfc872d695f5c26a)  should live, but they may be useful to include in the Node.js plugin somehow.

Please let me know if you feel like doing anything with them.

**Comment by segrey** [comment]
@boneskull Awesome, thanks! I'd say it's more Jasmine (or Mocha BDD) live templates, so they could live in JavaScriptLanguage plugin.

**Comment by boneskull** [comment]
Good point. I'll find it and send over there

**Comment by segrey** [comment]
It will be available in WebStorm 2017.3. EAP. I've altered it  bit ([javascript_testing.xml](https://gist.github.com/segrey/c5cfd8f74ca9d0cca0817374b5da6f7a)) to not suggest live templates in completion for common prefixes:
a -> af
b -> bf
ae -> afe
be -> bfe
desc -> descr
